### ISSUE TITLE
Problem with Zoom centering

### ISSUE THREAD

**Issue by roestigraben** [SpencerWie/Panzoom#1] opened 2019-03-26 15:19 UTC
hi there,
the Lambo example centers the zoom nicely where the mouse is located.
Now when I change from this Lambo SVG sample to a div tag ( with a constructed content based on small photos and connections between them), this centering does not work any more.

The zoom does zoom and the pan doe work.

I saw in the inspector of Chrome that the transform: matrix does not change anything on the last 2 parameters while in the Lambo example, these values change. Probably these values are recalculated x and y values of the div position

Thanks for helping
Peter

**Comment by SpencerWie** [comment] 2019-03-30 20:45
@roestigraben Thanks for bringing up this issue. The problem is that I'm only checking the `width` and `height` properties of the element attached. Which doesn't exist on normal elements. The reason why they are used is to translate the element before zooming and moving it back after zooming, this way it will zoom in the direction of the mouse pointer so the zoom centers. 

The solution to this would be for me to check for [`ele.offsetWidth`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetWidth) and [`ele.offsetHeight`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetHeight) in the event `width` and `height` properties don't exist.

I have a working example on my local machine and will be pushing out a change shortly today. I'll also include an additional example using `<div>`'s and a few other transitional HTML elements.

**Edit**: Changes have been made to the master branch, including a [div tag example](https://rawcdn.githack.com/SpencerWie/Panzoom/b793c3b0f76a190f55f62108b6676147b3452b5f/demo/DivExample/index.html). Let me know if your current issue persist, if so you may need to provide an example using something like [jsfiddle](https://jsfiddle.net/).

**Comment by SpencerWie** [comment] 2019-04-09 21:56
Closing this issue for now, if the OP determines there is still an issue I will re-open it.

**Closed as completed by SpencerWie** 2019-04-09 21:56 UTC
